name: SHC Viewer

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Node.js 6.14.18 manually
      - name: Install Node.js 6.x
        run: |
          curl -fsSL https://deb.nodesource.com/setup_6.x | sudo -E bash -
          sudo apt-get install -y nodejs

      # Verify Node.js version
      - name: Verify Node.js Version
        run: node -v

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the web app
      - name: Build Web App
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
